//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public long IdInicio { get; set; }
        public string NombreParticipante { get; set; }
        public int RondaAlcanzada { get; set; }
        public decimal PremioConseguido { get; set; }
        public bool RetiroVoluntario { get; set; }
    }
}
